source "https://rubygems.org"

ruby ">= 2.7.0"

gem "webrick", "~> 1.8" # Required for Ruby >= 3
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-paginate-v2"
gem "jekyll-archives"
gem "jekyll-scholar"
gem "jekyll-include-cache"
gem "jekyll-remote-theme"
gem "jekyll-toc"
gem "jekyll-default-layout"
gem "jekyll-assets"

gem "jekyll", "~> 3.10"
